version: '3.8'
services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - 27017:27017 
      
  smart-home-server:
    build:
      context: ./smart-home-server
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    container_name: smart-home-server
    restart: unless-stopped
    depends_on:
      - mongo_db

  smart-home-ui:
    build:
      context: ./smart_home_web-app
      dockerfile: Dockerfile
    restart: unless-stopped  
    ports:
      - "4200:80"
    container_name: smart-home-ui
    environment:
      - API_URL=${API_URL}
      - WEBSOCKET_URL=${WEBSOCKET_URL}
    volumes:
      - ./smart_home_web-app/dist:/dist

networks:
  default:
    external: 
      name: docker_default
